version: '2'
services:
    angular2jhipster-app:
        image: angular2jhipster
        external_links:
            - angular2jhipster-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/angular2jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angular2jhipster-mysql:
        extends:
            file: mysql.yml
            service: angular2jhipster-mysql
