version: '2'
services:
    angular2jhipster-mysql:
        container_name: angular2jhipster-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/angular2jhipster/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=angular2jhipster
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
